name: chat_tharwat
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  modal_progress_hud_nsn: ^0.4.0
  cloud_firestore: ^4.8.4
  animated_splash_screen: ^1.3.0
  flutter_launcher_icons: ^0.13.1
  flutter_bloc: ^8.1.3
  firebase_messaging: ^14.6.5
  flutter_local_notifications: ^15.1.0+1
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^8.0.0
  loading_animation_widget: ^1.2.0+4
  conditional_builder_null_safety: ^0.0.6
  flutter_staggered_grid_view:
  image_picker:
  firebase_storage:
  flutter_cache_manager: ^3.3.1
  device_preview: ^1.1.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/scholar.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Schyler
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: IconBroken
      fonts:
        - asset: assets/fonts/icons.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
